#version: '3.8' // Because docker 2.0 doesn't work with 3.8
# environment variable have been moved to the .env file

services:
  # To test localy the dashboard
  prosody:
    build:
      context: ./prosody
      dockerfile: Dockerfile
    container_name: spaderunner-prosody
    ports:
      - "5222:5222"  # XMPP client connections
      - "5269:5269"  # Server-to-server connections
      - "5280:5280"  # HTTP binding / BOSH (if enabled)
    volumes:
      - ./prosody/prosody-config:/etc/prosody   # Place your custom configuration files here
      - ./prosody/prosody-data:/var/lib/prosody   # Persistent data storage

    command: ["prosody"]
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spaderunner-app
    volumes:
      - .:/app
      - ./received_photos:/app/received_photos
      - ./calibration_photos:/app/calibration_photos
      - ./navigation_photos:/app/navigation_photos
      - ./logger_state:/app/logger_state

    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
      - "isc-coordinator2.lan:192.168.88.226"
#      - "isc-coordinator2.lan:192.168.31.163"
    env_file:
      - .env
    stdin_open: true # to let the container open to external signal
    tty: true # enable "keep the container running"
    ports:
      - "8080:8080"

  # For execution
  alphabot:
    build:
      context: .
      dockerfile: Dockerfile.AlphaBot2
    container_name: spaderunner-agent
    volumes:
      - .:/app
      - ./received_photos:/app/received_photos
      - ./calibration_photos:/app/calibration_photos
      - ./navigation_photos:/app/navigation_photos
      - ./logger_state:/app/logger_state
    ports:
      - "8080:8080" # Expose the app's HTTP endpoint for the logger/grafana flow
    #network_mode: "host"
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
      - "isc-coordinator2.lan:192.168.88.226"
    env_file:
      - .env
    stdin_open: true # to let the container open to external signal
    tty: true # enable "keep the container running"
  local:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: spaderunner-agent
    volumes:
      - .:/app
      - ./received_photos:/app/received_photos
      - ./calibration_photos:/app/calibration_photos
      - ./navigation_photos:/app/navigation_photos
      - ./logger_state:/app/logger_state
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
      - "isc-coordinator2.lan:192.168.88.226"
    env_file:
      - .env
    stdin_open: true # to let the container open to external signal
    tty: true # enable "keep the container running"
    ports:
      - "8080:8080"

volumes:
  prosody_data:
  prosody_config:
  prosody_logs: