#version: '3.8' // Because docker 2.0 doesn't work with 3.8
# environment variable have been moved to the .env file

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./received_photos:/app/received_photos
      - ./calibration_photos:/app/calibration_photos
    network_mode: "host"
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
      - "isc-coordinator2.lan:192.168.88.226"
    env_file:
      - .env
    stdin_open: true # to let the container open to external signal
    tty: true # enable "keep the container running"