#!/bin/bash
# Deployment script for SpadeRunner
LOGFILE=deploy.log
echo "$(date) - Deployment started" >> $LOGFILE
echo "$(date) - Deployment started"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_PATH="${SCRIPT_DIR}"

# Load .env file (local config for deployment)
ENV_FILE="${LOCAL_PATH}/.env"
if [ -f $ENV_FILE ]; then
    source $ENV_FILE
else
    echo "$ENV_FILE file not found" >> $LOGFILE
    echo "$ENV_FILE file not found"
    exit 1
fi

# Select bot to deploy on (limitation implied by the labo)
read -rp "Select bot to deploy on (1 or 3): " bot_choice
if [[ ! $bot_choice =~ ^[13]$ ]]; then
    echo "Invalid bot id, choice ${bot_choice}. Exiting." >> $LOGFILE
    echo "Invalid bot id, choice ${bot_choice}. Exiting."
    exit 1
fi

# Select XMPP coordinator (server) the bot's agents will connect to
read -rp "Select XMPP coordinator the bot will connect to (1-2): " coordinator
if [[ ! $coordinator =~ ^[1-2|p]$ ]]; then
    echo "Invalid XMPP coordinator choice ${coordinator}. Exiting." >> $LOGFILE
    echo "Invalid XMPP coordinator choice ${coordinator}. Exiting."
    exit 1
fi

REMOTE_HOST_VAR="REMOTE_HOST_${bot_choice}"
XMPP_DOMAIN_VAR="XMPP_DOMAIN_${coordinator}"

REMOTE_HOST="${!REMOTE_HOST_VAR}"
XMPP_DOMAIN="${!XMPP_DOMAIN_VAR}"

# Generate .env file for the selected bot
TEMPLATE="${LOCAL_PATH}/.env.template"
OUTPUT="${LOCAL_PATH}/.env.temp"

if [ ! -f "$TEMPLATE" ]; then
    echo "Missing .env.template in SpadeRunner" >> $LOGFILE
    echo "Missing .env.template in SpadeRunner"
    exit 1
fi

cp "$TEMPLATE" "$OUTPUT"

# Add header comment
tmpfile=$(mktemp)
{
    echo "# ---------------------------------------------------------"
    echo "# This file was generated automatically by deploy_code.sh"
    echo "# Do NOT edit this file manually."
    echo "# If you need to change values, edit .env.template"
    echo "# ---------------------------------------------------------"
    echo
    echo "# Generated for bot $bot_choice connecting to XMPP coordinator $coordinator"
    echo
    cat "$OUTPUT"
} > "$tmpfile"

mv "$tmpfile" "$OUTPUT"

sed -i "s|{{REMOTE_HOST}}|$REMOTE_HOST|g" "$OUTPUT"
sed -i "s|{{XMPP_DOMAIN}}|$XMPP_DOMAIN|g" "$OUTPUT"
sed -i "s|{{ROBOT_NUM}}|$bot_choice|g" "$OUTPUT"


echo "Generated .env for bot $bot_choice (XMPP coordinator $coordinator)" >> $LOGFILE
echo "Generated .env for bot $bot_choice (XMPP coordinator $coordinator)"
# ---------------------------------------------------------

# Default values
SSH_PORT=${SSH_PORT:-22}
RSYNC_OPTS=${RSYNC_OPTS:--avz --delete}

# Notice if the deployment is local or on an AlphaBot2-Pi
if [[ $coordinator == 'p' ]]; then
    echo "Prosody domain is only for test don't deploy it on a bot."
fi
read -rp "Does it will run locally (on the PC)? (y/n) " locally
if [[ $locally != "y" ]]; then
    sed -i "s|{{REMOTE_MODE}}|REMOTE|g" "$OUTPUT"
    echo "Deploying folder to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}" >> $LOGFILE
    echo "Using rsync options: ${RSYNC_OPTS}" >> $LOGFILE
    echo "XMPP base JID will be: ${XMPP_DOMAIN}" >> $LOGFILE
    echo "Deploying folder to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
    echo "Using rsync options: ${RSYNC_OPTS}"
    echo "XMPP base JID will be: ${XMPP_DOMAIN}"
else
    sed -i "s|{{REMOTE_MODE}}|LOCAL|g" "$OUTPUT"
    echo "Local deployment on the PC" >> $LOGFILE
    echo "XMPP base JID will be: ${XMPP_DOMAIN}" >> $LOGFILE
    echo "Local deployment on the PC"
    echo "XMPP base JID will be: ${XMPP_DOMAIN}"
fi


echo "WARNING: This will override the local .env file."
read -rp "Do you want to update .env file? (y/n) " env
if [[ $env = "y" ]]; then
    mv $OUTPUT $ENV_FILE
else
    echo "Deploiment aborted." >> $LOGFILE
    echo "Deploiment aborted."
    rm $OUTPUT
    exit 0
fi

# Confirm deployment

if [[ $locally != "y" ]]; then
    echo "WARNING: This will DELETE files on the remote side that are not present locally."
    read -rp "Proceed with deployment? (y/n) " confirm
    [[ "$confirm" != "y" ]] && exit 0
    # Run rsync
    rsync ${RSYNC_OPTS} -e "ssh -p ${SSH_PORT}" \
        "${LOCAL_PATH}/" \
        "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/"

    echo "Deployment complete on  ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}." >> $LOGFILE
    echo "Deployment complete on  ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}."
fi
